In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/IMDB_Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## 1. Lowercasing

In [4]:
df['review'] = df['review'].apply(lambda x : x.lower())

In [5]:
df.sample(5)

                                                  review sentiment
7719   this movie makes several mistakes. a few ameri...  negative
882    how can so many blundering decisions can be ma...  negative
6082   the worst movie i have seen in quite a while. ...  negative
13376  it was the worst ending i have ever seen if so...  negative
47025  i was previously unaware that in the early 199...  negative

## 2. Removing HTML Tags

In [6]:
import re

pattern = re.compile(r"<[^>]*>")

df['review'] = df['review'].apply(lambda x: pattern.sub("",x))

In [7]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

## 3. Removing URLs

In [8]:
(df['review'].apply(lambda x:"www." in x)).value_counts()

review
False    49855
True       145
Name: count, dtype: int64

In [9]:
(df['review'].apply(lambda x:"http://" in x)).value_counts()

review
False    49880
True       120
Name: count, dtype: int64

In [10]:
pattern = re.compile(r"(?:https?://|www\.)[^\s]+")

df['review'] = df['review'].apply(lambda x : pattern.sub("", x))

In [11]:
(df['review'].apply(lambda x:"http://" in x)).value_counts()

review
False    50000
Name: count, dtype: int64

In [12]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

## 4. Removing Punctuation

In [13]:
import string
puctuations = string.punctuation

In [14]:
def remove_puntuations(sent):
    return sent.translate(str.maketrans("","",puctuations))

In [15]:
df['review'] = df['review'].apply(remove_puntuations)

In [16]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

## 5. Chat Word Treatment (Slang Expansion)

eg: ASAP -> As Soon As Possible

In [17]:
chat_words_dict = {}
with open("data/english_chat_words.txt","r") as file:
    for f in file.readlines():
        chat_words_dict[f.split("->")[0].strip()] = f.split("->")[1].strip()

In [18]:
def remove_chatwords(sentence):
    result = str(sentence)
    for word in sentence.split(" "):
        if word.upper() in chat_words_dict:
            print(word)
            print(chat_words_dict[word.upper()])
            result = result.replace(word, chat_words_dict[word.upper()])
    return result

In [19]:
df['review'] = df['review'].apply(remove_chatwords)

til
Today I Learned
til
Today I Learned
btw
By The Way
aka
Also Known As
ty
Thank You
u
You
ppl
People
ppl
People
ur
Your / You Are
aka
Also Known As
wb
Welcome Back
aka
Also Known As
aka
Also Known As
diy
Do It Yourself
pc
Personal Computer
ty
Thank You
y
Why
y
Why
wb
Welcome Back
u
You
pc
Personal Computer
aka
Also Known As
u
You
u
You
tia
Thanks In Advance
aka
Also Known As
aka
Also Known As
pov
Point Of View
u
You
omg
Oh My God
btw
By The Way
y
Why
wb
Welcome Back
u
You
u
You
imho
In My Humble Opinion
lol
Laugh Out Loud
u
You
ftw
For The Win
y
Why
u
You
til
Today I Learned
aka
Also Known As
imo
In My Opinion
aka
Also Known As
y
Why
vip
Very Important Person
til
Today I Learned
eod
End Of Day
gr8
Great
gr8
Great
u
You
ty
Thank You
ty
Thank You
atm
At The Moment
wb
Welcome Back
til
Today I Learned
sos
Save Our Souls (Help)
til
Today I Learned
btw
By The Way
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
btw
By The Way
pc
Personal Computer
til
Today I Learned
aka
Also Known As
asap
As Soon As Possible
aka
Also Known As
pc
Personal Computer
aka
Also Known As
aka
Also Known As
ur
Your / You Are
wcw
Woman Crush Wednesday
wcw
Woman Crush Wednesday
imho
In My Humble Opinion
y
Why
btw
By The Way
pov
Point Of View
thx
Thanks
wtf
What The F***
aka
Also Known As
y
Why
sos
Save Our Souls (Help)
iirc
If I Remember Correctly
otoh
On The Other Hand
lol
Laugh Out Loud
aka
Also Known As
aka
Also Known As
imo
In My Opinion
pc
Personal Computer
aka
Also Known As
aka
Also Known As
lol
Laugh Out Loud
wcw
Woman Crush Wednesday
wcw
Woman Crush Wednesday
wcw
Woman Crush Wednesday
lol
Laugh Out Loud
pc
Personal Computer
pov
Point Of View
asap
As Soon As Possible
aka
Also Known As
imho
In My Humble Opinion
wtf
What The F***
aka
Also Known As
fyi
For Your Information
imo
In My Opinion
aka
Also Known As
lol
Laugh Out Loud
u
You
aka
Also Known As
wtf
What The F***
rn
Right Now
aka
Also Known As
btw
By The Way
ty
Thank You
imo
In My Opinion
imho
In My Humble Opinion
imo
In My Opinion
imo
In My Opinion
lol
Laugh Out Loud
aka
Also Known As
op
Original Poster
u
You
wtf
What The F***
thx
Thanks
wb
Welcome Back
aka
Also Known As
aka
Also Known As
btw
By The Way
cc
Carbon Copy
cc
Carbon Copy
lol
Laugh Out Loud
aka
Also Known As
lol
Laugh Out Loud
imho
In My Humble Opinion
lol
Laugh Out Loud
aka
Also Known As
diy
Do It Yourself
aka
Also Known As
aka
Also Known As
lol
Laugh Out Loud
aka
Also Known As
pc
Personal Computer
sos
Save Our Souls (Help)
aka
Also Known As
pc
Personal Computer
aka
Also Known As
aka
Also Known As
y
Why
bd
Big Deal
sos
Save Our Souls (Help)
u
You
aka
Also Known As
til
Today I Learned
imho
In My Humble Opinion
pc
Personal Computer
pc
Personal Computer
wtf
What The F***
thx
Thanks
u
You
u
You
u
You
u
You
lol
Laugh Out Loud
aka
Also Known As
aka
Also Known As
u
You
aka
Also Known As
u
You
ty
Thank You
aka
Also Known As
pc
Personal Computer
pc
Personal Computer
u
You
u
You
ur
Your / You Are
hw
Homework
hw
Homework
aka
Also Known As
ppl
People
ppl
People
ppl
People
wtf
What The F***
lol
Laugh Out Loud
imo
In My Opinion
lol
Laugh Out Loud
omg
Oh My God
y
Why
til
Today I Learned
btw
By The Way
imo
In My Opinion
u
You
lol
Laugh Out Loud
lol
Laugh Out Loud
tia
Thanks In Advance
wb
Welcome Back
wb
Welcome Back
wb
Welcome Back
lol
Laugh Out Loud
gg
Good Game
gg
Good Game
aka
Also Known As
aka
Also Known As
aka
Also Known As
btw
By The Way
wtf
What The F***
til
Today I Learned
til
Today I Learned
ur
Your / You Are
aka
Also Known As
lol
Laugh Out Loud
aka
Also Known As
aka
Also Known As
imo
In My Opinion
pc
Personal Computer
pc
Personal Computer
imo
In My Opinion
aka
Also Known As
imo
In My Opinion
imo
In My Opinion
diy
Do It Yourself
pov
Point Of View
lol
Laugh Out Loud
aka
Also Known As
vip
Very Important Person
pov
Point Of View
aka
Also Known As
imo
In My Opinion
aka
Also Known As
bcc
Blind Carbon Copy
aka
Also Known As
u
You
omg
Oh My God
pc
Personal Computer
u
You
lol
Laugh Out Loud
pc
Personal Computer
btw
By The Way
aka
Also Known As
aka
Also Known As
btw
By The Way
btw
By The Way
btw
By The Way
bd
Big Deal
bd
Big Deal
vip
Very Important Person
vip
Very Important Person
aka
Also Known As
pc
Personal Computer
omg
Oh My God
u
You
pov
Point Of View
omg
Oh My God
wtf
What The F***
omg
Oh My God
lol
Laugh Out Loud
tia
Thanks In Advance
bd
Big Deal
til
Today I Learned
imo
In My Opinion
wtf
What The F***
aka
Also Known As
wtf
What The F***
wtf
What The F***
lol
Laugh Out Loud
u
You
aka
Also Known As
ppl
People
ppl
People
aka
Also Known As
ty
Thank You
ty
Thank You
y
Why
btw
By The Way
omg
Oh My God
u
You
til
Today I Learned
fyi
For Your Information
aka
Also Known As
hw
Homework
u
You
u
You
til
Today I Learned
pc
Personal Computer
omg
Oh My God
imho
In My Humble Opinion
wb
Welcome Back
imo
In My Opinion
u
You
u
You
aka
Also Known As
aka
Also Known As
y
Why
y
Why
btw
By The Way
u
You
ty
Thank You
ty
Thank You
ty
Thank You
wtf
What The F***
wtf
What The F***
aka
Also Known As
pc
Personal Computer
imo
In My Opinion
aka
Also Known As
u
You
ur
Your / You Are
imo
In My Opinion
wtf
What The F***
ty
Thank You
y
Why
u
You
u
You
u
You
u
You
y
Why
u
You
pov
Point Of View
aka
Also Known As
wtf
What The F***
atm
At The Moment
til
Today I Learned
pc
Personal Computer
aka
Also Known As
til
Today I Learned
aka
Also Known As
u
You
btw
By The Way
asap
As Soon As Possible
imo
In My Opinion
pov
Point Of View
lol
Laugh Out Loud
u
You
aka
Also Known As
vip
Very Important Person
u
You
pov
Point Of View
aka
Also Known As
aka
Also Known As
u
You
u
You
lol
Laugh Out Loud
pc
Personal Computer
aka
Also Known As
wb
Welcome Back
aka
Also Known As
aka
Also Known As
pov
Point Of View
pc
Personal Computer
aka
Also Known As
lol
Laugh Out Loud
pc
Personal Computer
wtf
What The F***
wtf
What The F***
aka
Also Known As
aka
Also Known As
aka
Also Known As
pov
Point Of View
imo
In My Opinion
imho
In My Humble Opinion
aka
Also Known As
pc
Personal Computer
wtf
What The F***
wtf
What The F***
aka
Also Known As
aka
Also Known As
eta
Estimated Time Of Arrival
aka
Also Known As
tc
Take Care
aka
Also Known As
aka
Also Known As
u
You
tia
Thanks In Advance
wtf
What The F***
imo
In My Opinion
til
Today I Learned
til
Today I Learned
aka
Also Known As
aka
Also Known As
aka
Also Known As
wtf
What The F***
aka
Also Known As
lol
Laugh Out Loud
aka
Also Known As
u
You
cob
Close Of Business
wtf
What The F***
aka
Also Known As
omg
Oh My God
wtf
What The F***
wtf
What The F***
tia
Thanks In Advance
wb
Welcome Back
aka
Also Known As
btw
By The Way
pc
Personal Computer
btw
By The Way
aka
Also Known As
imho
In My Humble Opinion
ty
Thank You
btw
By The Way
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
imho
In My Humble Opinion
u
You
wtf
What The F***
wtf
What The F***
u
You
wtf
What The F***
wtf
What The F***
aka
Also Known As
lol
Laugh Out Loud
aka
Also Known As
imho
In My Humble Opinion
omg
Oh My God
lol
Laugh Out Loud
aka
Also Known As
op
Original Poster
wb
Welcome Back
cc
Carbon Copy
lol
Laugh Out Loud
lol
Laugh Out Loud
lol
Laugh Out Loud
u
You
u
You
aka
Also Known As
aka
Also Known As
afaik
As Far As I Know
imho
In My Humble Opinion
aka
Also Known As
pov
Point Of View
pov
Point Of View
wtf
What The F***
til
Today I Learned
aka
Also Known As
lol
Laugh Out Loud
u
You
imo
In My Opinion
u
You
u
You
imho
In My Humble Opinion
lol
Laugh Out Loud
afaik
As Far As I Know
aka
Also Known As
idk
I Don't Know
omg
Oh My God
aka
Also Known As
u
You
omg
Oh My God
aka
Also Known As
wip
Work In Progress
aka
Also Known As
wip
Work In Progress
dm
Direct Message
aka
Also Known As
btw
By The Way
gm
Good Morning
aka
Also Known As
btw
By The Way
omg
Oh My God
aka
Also Known As
lol
Laugh Out Loud
u
You
irl
In Real Life
btw
By The Way
lol
Laugh Out Loud
pov
Point Of View
aka
Also Known As
u
You
wcw
Woman Crush Wednesday
wtf
What The F***
cc
Carbon Copy
tia
Thanks In Advance
aka
Also Known As
pov
Point Of View
aka
Also Known As
ppl
People
op
Original Poster
asap
As Soon As Possible
pc
Personal Computer
fyi
For Your Information
aka
Also Known As
lol
Laugh Out Loud
u
You
aka
Also Known As
u
You
wb
Welcome Back
wb
Welcome Back
imo
In My Opinion
btw
By The Way
y
Why
aka
Also Known As
wtf
What The F***
lol
Laugh Out Loud
u
You
imo
In My Opinion
pc
Personal Computer
u
You
aka
Also Known As
u
You
pc
Personal Computer
btw
By The Way
u
You
aka
Also Known As
lol
Laugh Out Loud
lol
Laugh Out Loud
u
You
u
You
u
You
u
You
pc
Personal Computer
pc
Personal Computer
lol
Laugh Out Loud
til
Today I Learned
aka
Also Known As
wtf
What The F***
y
Why
u
You
ur
Your / You Are
wip
Work In Progress
wip
Work In Progress
wip
Work In Progress
pc
Personal Computer
pc
Personal Computer
aka
Also Known As
imho
In My Humble Opinion
pov
Point Of View
u
You
u
You
u
You
imo
In My Opinion
lol
Laugh Out Loud
wb
Welcome Back
til
Today I Learned
btw
By The Way
imo
In My Opinion
aka
Also Known As
sos
Save Our Souls (Help)
ur
Your / You Are
u
You
wb
Welcome Back
msg
Message
imo
In My Opinion
pov
Point Of View
btw
By The Way
u
You
u
You
u
You
omg
Oh My God
omg
Oh My God
y
Why
aka
Also Known As
aka
Also Known As
til
Today I Learned
pc
Personal Computer
btw
By The Way
cob
Close Of Business
wcw
Woman Crush Wednesday
wcw
Woman Crush Wednesday
wtf
What The F***
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
sry
Sorry
aka
Also Known As
omg
Oh My God
sos
Save Our Souls (Help)
u
You
aka
Also Known As
lol
Laugh Out Loud
btw
By The Way
aka
Also Known As
thx
Thanks
pc
Personal Computer
wtf
What The F***
lmao
Laughing My Ass Off
wcw
Woman Crush Wednesday
aka
Also Known As
tia
Thanks In Advance
tia
Thanks In Advance
diy
Do It Yourself
imo
In My Opinion
jk
Just Kidding
cc
Carbon Copy
wb
Welcome Back
wb
Welcome Back
omg
Oh My God
btw
By The Way
imho
In My Humble Opinion
u
You
imo
In My Opinion
wtf
What The F***
imho
In My Humble Opinion
aka
Also Known As
y
Why
diy
Do It Yourself
eod
End Of Day
aka
Also Known As
lol
Laugh Out Loud
btw
By The Way
rofl
Rolling On The Floor Laughing
til
Today I Learned
aka
Also Known As
gm
Good Morning
cc
Carbon Copy
wtf
What The F***
ty
Thank You
btw
By The Way
u
You
u
You
pc
Personal Computer
gm
Good Morning
pc
Personal Computer
cc
Carbon Copy
u
You
imo
In My Opinion
u
You
aka
Also Known As
u
You
wtf
What The F***
wb
Welcome Back
u
You
pc
Personal Computer
u
You
rn
Right Now
til
Today I Learned
imo
In My Opinion
pov
Point Of View
u
You
u
You
plz
Please
nvm
Nevermind
til
Today I Learned
imho
In My Humble Opinion
btw
By The Way
asap
As Soon As Possible
u
You
imo
In My Opinion
wtf
What The F***
asap
As Soon As Possible
aka
Also Known As
u
You
u
You
u
You
u
You
wtf
What The F***
til
Today I Learned
jk
Just Kidding
u
You
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
atm
At The Moment
aka
Also Known As
aka
Also Known As
aka
Also Known As
u
You
u
You
btw
By The Way
wb
Welcome Back
aka
Also Known As
til
Today I Learned
u
You
wtf
What The F***
bd
Big Deal
fyi
For Your Information
asap
As Soon As Possible
u
You
u
You
lol
Laugh Out Loud
vip
Very Important Person
vip
Very Important Person
u
You
aka
Also Known As
til
Today I Learned
aka
Also Known As
lol
Laugh Out Loud
pc
Personal Computer
aka
Also Known As
imho
In My Humble Opinion
wtf
What The F***
aka
Also Known As
ppl
People
lol
Laugh Out Loud
y
Why
aka
Also Known As
lol
Laugh Out Loud
diy
Do It Yourself
aka
Also Known As
aka
Also Known As
wtf
What The F***
lol
Laugh Out Loud
aka
Also Known As
aka
Also Known As
pc
Personal Computer
sos
Save Our Souls (Help)
aka
Also Known As
u
You
u
You
pc
Personal Computer
aka
Also Known As
aka
Also Known As
imho
In My Humble Opinion
aka
Also Known As
aka
Also Known As
u
You
lol
Laugh Out Loud
op
Original Poster
plz
Please
aka
Also Known As
wtf
What The F***
u
You
lol
Laugh Out Loud
gr8
Great
u
You
lol
Laugh Out Loud
omg
Oh My God
fwiw
For What It Is Worth
lol
Laugh Out Loud
u
You
ur
Your / You Are
u
You
tia
Thanks In Advance
tia
Thanks In Advance
tia
Thanks In Advance
tia
Thanks In Advance
tia
Thanks In Advance
plz
Please
plz
Please
plz
Please
btw
By The Way
plz
Please
imho
In My Humble Opinion
aka
Also Known As
aka
Also Known As
u
You
btw
By The Way
aka
Also Known As
lol
Laugh Out Loud
pc
Personal Computer
y
Why
omg
Oh My God
wb
Welcome Back
imo
In My Opinion
pov
Point Of View
aka
Also Known As
ppl
People
asap
As Soon As Possible
til
Today I Learned
imo
In My Opinion
u
You
til
Today I Learned
u
You
u
You
u
You
aka
Also Known As
imo
In My Opinion
aka
Also Known As
tia
Thanks In Advance
imho
In My Humble Opinion
aka
Also Known As
lol
Laugh Out Loud
aka
Also Known As
wtf
What The F***
u
You
ur
Your / You Are
tia
Thanks In Advance
pc
Personal Computer
wb
Welcome Back
u
You
u
You
u
You
u
You
u
You
u
You
vip
Very Important Person
dm
Direct Message
aka
Also Known As
lol
Laugh Out Loud
wip
Work In Progress
ppl
People
u
You
imho
In My Humble Opinion
lol
Laugh Out Loud
aka
Also Known As
asap
As Soon As Possible
aka
Also Known As
u
You
aka
Also Known As
pc
Personal Computer
y
Why
ty
Thank You
u
You
ppl
People
u
You
u
You
u
You
plz
Please
y
Why
lol
Laugh Out Loud
fyi
For Your Information
eod
End Of Day
aka
Also Known As
aka
Also Known As
btw
By The Way
btw
By The Way
til
Today I Learned
imho
In My Humble Opinion
wtf
What The F***
wtf
What The F***
lmao
Laughing My Ass Off
lol
Laugh Out Loud
ur
Your / You Are
ur
Your / You Are
u
You
bff
Best Friends Forever
wtf
What The F***
btw
By The Way
aka
Also Known As
aka
Also Known As
pov
Point Of View
pc
Personal Computer
jk
Just Kidding
jk
Just Kidding
imo
In My Opinion
imo
In My Opinion
tia
Thanks In Advance
imho
In My Humble Opinion
wtf
What The F***
wtf
What The F***
imho
In My Humble Opinion
aka
Also Known As
aka
Also Known As
gg
Good Game
omg
Oh My God
wtf
What The F***
aka
Also Known As
pc
Personal Computer
u
You
u
You
u
You
lol
Laugh Out Loud
thx
Thanks
wtf
What The F***
gg
Good Game
u
You
u
You
u
You
aka
Also Known As
u
You
u
You
u
You
u
You
bd
Big Deal
aka
Also Known As
btw
By The Way
lol
Laugh Out Loud
u
You
pc
Personal Computer
wtf
What The F***
u
You
u
You
til
Today I Learned
lol
Laugh Out Loud
y
Why
tia
Thanks In Advance
pc
Personal Computer
pc
Personal Computer
pc
Personal Computer
imho
In My Humble Opinion
wip
Work In Progress
wip
Work In Progress
wip
Work In Progress
u
You
wtf
What The F***
imo
In My Opinion
lol
Laugh Out Loud
rn
Right Now
u
You
u
You
u
You
btw
By The Way
pc
Personal Computer
btw
By The Way
btw
By The Way
u
You
y
Why
lol
Laugh Out Loud
lol
Laugh Out Loud
lol
Laugh Out Loud
pov
Point Of View
ily
I Love You
gm
Good Morning
imo
In My Opinion
imo
In My Opinion
pov
Point Of View
imho
In My Humble Opinion
pov
Point Of View
u
You
bff
Best Friends Forever
asap
As Soon As Possible
u
You
y
Why
pc
Personal Computer
u
You
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
u
You
diy
Do It Yourself
lol
Laugh Out Loud
btw
By The Way
aka
Also Known As
til
Today I Learned
omg
Oh My God
aka
Also Known As
ty
Thank You
ty
Thank You
u
You
u
You
rn
Right Now
btw
By The Way
aka
Also Known As
pc
Personal Computer
u
You
omg
Oh My God
aka
Also Known As
btw
By The Way
u
You
aka
Also Known As
thx
Thanks
btw
By The Way
aka
Also Known As
thx
Thanks
imo
In My Opinion
til
Today I Learned
lol
Laugh Out Loud
aka
Also Known As
imo
In My Opinion
imo
In My Opinion
aka
Also Known As
wb
Welcome Back
aka
Also Known As
aka
Also Known As
lol
Laugh Out Loud
pc
Personal Computer
u
You
aka
Also Known As
lol
Laugh Out Loud
lol
Laugh Out Loud
lol
Laugh Out Loud
aka
Also Known As
diy
Do It Yourself
vip
Very Important Person
aka
Also Known As
vip
Very Important Person
tmi
Too Much Information
imho
In My Humble Opinion
imho
In My Humble Opinion
imho
In My Humble Opinion
u
You
gm
Good Morning
asap
As Soon As Possible
imo
In My Opinion
lol
Laugh Out Loud
imo
In My Opinion
wtf
What The F***
lol
Laugh Out Loud
til
Today I Learned
lol
Laugh Out Loud
wb
Welcome Back
wb
Welcome Back
wb
Welcome Back
wb
Welcome Back
aka
Also Known As
btw
By The Way
tia
Thanks In Advance
tia
Thanks In Advance
asap
As Soon As Possible
imo
In My Opinion
aka
Also Known As
imo
In My Opinion
u
You
u
You
imho
In My Humble Opinion
y
Why
aka
Also Known As
gm
Good Morning
wtf
What The F***
u
You
wtf
What The F***
wtf
What The F***
imo
In My Opinion
u
You
aka
Also Known As
aka
Also Known As
pc
Personal Computer
u
You
sos
Save Our Souls (Help)
u
You
u
You
u
You
u
You
u
You
aka
Also Known As
pov
Point Of View
dm
Direct Message
dm
Direct Message
dm
Direct Message
lol
Laugh Out Loud
rofl
Rolling On The Floor Laughing
atm
At The Moment
lol
Laugh Out Loud
aka
Also Known As
btw
By The Way
til
Today I Learned
pov
Point Of View
pov
Point Of View
aka
Also Known As
til
Today I Learned
eta
Estimated Time Of Arrival
aka
Also Known As
gm
Good Morning
wtf
What The F***
u
You
u
You
pc
Personal Computer
pc
Personal Computer
til
Today I Learned
aka
Also Known As
aka
Also Known As
pc
Personal Computer
lol
Laugh Out Loud
ty
Thank You
pc
Personal Computer
u
You
wb
Welcome Back
pc
Personal Computer
tia
Thanks In Advance
lol
Laugh Out Loud
lol
Laugh Out Loud
lol
Laugh Out Loud
eta
Estimated Time Of Arrival
aka
Also Known As
lol
Laugh Out Loud
tbh
To Be Honest
lol
Laugh Out Loud
roi
Return On Investment
dnd
Do Not Disturb
dnd
Do Not Disturb
lol
Laugh Out Loud
lol
Laugh Out Loud
aka
Also Known As
btw
By The Way
aka
Also Known As
imho
In My Humble Opinion
aka
Also Known As
u
You
u
You
ooo
Out Of Office
btw
By The Way
pov
Point Of View
u
You
tc
Take Care
aka
Also Known As
cob
Close Of Business
wtf
What The F***
pc
Personal Computer
aka
Also Known As
imo
In My Opinion
aka
Also Known As
omg
Oh My God
imho
In My Humble Opinion
aka
Also Known As
pov
Point Of View
til
Today I Learned
aka
Also Known As
aka
Also Known As
dm
Direct Message
imo
In My Opinion
aka
Also Known As
lol
Laugh Out Loud
u
You
aka
Also Known As
aka
Also Known As
aka
Also Known As
btw
By The Way
lol
Laugh Out Loud
lmao
Laughing My Ass Off
omg
Oh My God
aka
Also Known As
lol
Laugh Out Loud
omg
Oh My God
lol
Laugh Out Loud
btw
By The Way
omg
Oh My God
imo
In My Opinion
bd
Big Deal
til
Today I Learned
til
Today I Learned
aka
Also Known As
aka
Also Known As
lol
Laugh Out Loud
wtf
What The F***
pov
Point Of View
btw
By The Way
imo
In My Opinion
aka
Also Known As
aka
Also Known As
pc
Personal Computer
aka
Also Known As
wtf
What The F***
aka
Also Known As
aka
Also Known As
vip
Very Important Person
asap
As Soon As Possible
aka
Also Known As
wb
Welcome Back
wb
Welcome Back
wb
Welcome Back
u
You
u
You
ur
Your / You Are
til
Today I Learned
u
You
u
You
u
You
u
You
imho
In My Humble Opinion
lol
Laugh Out Loud
y
Why
aka
Also Known As
imho
In My Humble Opinion
imo
In My Opinion
pc
Personal Computer
omg
Oh My God
lol
Laugh Out Loud
til
Today I Learned
til
Today I Learned
u
You
pc
Personal Computer
ty
Thank You
u
You
aka
Also Known As
cc
Carbon Copy
wb
Welcome Back
btw
By The Way
aka
Also Known As
u
You
u
You
u
You
imho
In My Humble Opinion
aka
Also Known As
pc
Personal Computer
cob
Close Of Business
u
You
lol
Laugh Out Loud
pov
Point Of View
imo
In My Opinion
aka
Also Known As
aka
Also Known As
wtf
What The F***
wtf
What The F***
lol
Laugh Out Loud
lol
Laugh Out Loud
lol
Laugh Out Loud
lol
Laugh Out Loud
u
You
sos
Save Our Souls (Help)
aka
Also Known As
btw
By The Way
u
You
op
Original Poster
btw
By The Way
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
imo
In My Opinion
u
You
aka
Also Known As
aka
Also Known As
btw
By The Way
aka
Also Known As
aka
Also Known As
y
Why
lol
Laugh Out Loud
aka
Also Known As
til
Today I Learned
wtf
What The F***
til
Today I Learned
pc
Personal Computer
gm
Good Morning
aka
Also Known As
aka
Also Known As
pov
Point Of View
aka
Also Known As
aka
Also Known As
pov
Point Of View
aka
Also Known As
aka
Also Known As
lol
Laugh Out Loud
til
Today I Learned
pov
Point Of View
lol
Laugh Out Loud
imho
In My Humble Opinion
diy
Do It Yourself
lol
Laugh Out Loud
lol
Laugh Out Loud
imo
In My Opinion
lol
Laugh Out Loud
pov
Point Of View
aka
Also Known As
aka
Also Known As

In [20]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

## Removing stopwords

In [21]:
from nltk.corpus import stopwords
import nltk
nltk.data.path.append('/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [22]:
def remove_stopwords(sentence):
    li = []

    for word in sentence.split(" "):
        if word not in stopwords.words('english'):
            li.append(word)
    return " ".join(li)

In [23]:
df['review'] = df['review'].apply(remove_stopwords)

## Handling Emoji

In [24]:
import emoji

emoji.replace_emoji("I love NLP 🤖🔥", "")

'I love NLP '

In [25]:
df['review'].apply(lambda x: emoji.replace_emoji(x, ""))

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production filming technique ...
2        thought wonderful way spend time hot summer we...
3        basically theres family little boy jake thinks...
4        petter matteis love time money visually stunni...
                               ...
49995    thought movie right good job wasnt creative or...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    catholic taught parochial elementary schools n...
49998    im going disagree previous comment side maltin...
49999    one expects star trek movies high art fans exp...
Name: review, Length: 50000, dtype: str

## Spelling Correction

In [26]:
from textblob import TextBlob

# textblob = TextBlob()
# textblob.correct.string()

In [27]:
from symspellpy import SymSpell, Verbosity
import pkg_resources

symspell = SymSpell(max_dictionary_edit_distance=2)

dictionary_path = pkg_resources.resource_filename(
    "symspellpy", "frequency_dictionary_en_82_765.txt",
)
symspell.load_dictionary(dictionary_path, term_index=0, count_index=1)


def fix_spelling(sentence):
    suggestions = symspell.lookup_compound(sentence, max_edit_distance=2)
    return suggestions[0].term

/tmp/ipykernel_12711/118613185.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [28]:
symspell.lookup_compound("one reviewrs mentin watch 1 oz epiode youll", max_edit_distance=2)[0].term

"one reviews mention watch a of episode you'll"

In [29]:
df['review'] = df['review'].apply(fix_spelling)

## Lemmatizer

In [30]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

In [31]:
nltk.pos_tag(nltk.word_tokenize("one reviewers mention watch 1 oz episode youll"))

[('one', 'CD'),
 ('reviewers', 'NNS'),
 ('mention', 'VBP'),
 ('watch', 'VB'),
 ('1', 'CD'),
 ('oz', 'JJ'),
 ('episode', 'NN'),
 ('youll', 'NN')]

In [32]:
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [33]:
lemmatizer = WordNetLemmatizer()

def lemmatize_words(sentence):
    tokens = nltk.word_tokenize(sentence)
    pos_tags = nltk.pos_tag(tokens=tokens)
    result = []
    
    for word in pos_tags:
        result.append(lemmatizer.lemmatize(word=word[0],pos=get_wordnet_pos(word[1])))
    return " ".join(result)

In [34]:
df['review'] = df['review'].apply(lemmatize_words)

In [35]:
df.head()

                                              review sentiment
0  one reviewer mention watch a of episode you 'l...  positive
1  wonderful little production film technique una...  positive
2  think wonderful way spend time hot summer week...  positive
3  basically there family little boy jake think t...  negative
4  petter matter love time money visually stunnin...  positive

## One Hot encoding

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

In [37]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [38]:
df_copy = df.copy()

In [39]:
df.head()

                                              review sentiment
0  one reviewer mention watch a of episode you 'l...  positive
1  wonderful little production film technique una...  positive
2  think wonderful way spend time hot summer week...  positive
3  basically there family little boy jake think t...  negative
4  petter matter love time money visually stunnin...  positive

In [45]:
df.to_csv("data/IMDB_processed_data.csv")

In [40]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first',sparse_output=False)


df_num = ohe.fit_transform(df[['review']])

In [41]:
df_num

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(50000, 49570))

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

x = cv.fit_transform(df['review'])

In [43]:
type(x)

scipy.sparse._csr.csr_matrix

In [44]:
# x.toarray()