In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("data/movies_data.csv")
df.sample(5)

,title,genre,language,casts,description,release_date
4721,Puthiya Theerppu,"Action, Comedy",ta,"Vijayakanth (), Ambika (), Senthil (), Janagar...",NaN,1985-10-04
7494,Zimbabwe,Drama,en,"Kudzai Chimbaira (Zimbabwe), Farai Veremu (Dum...","Amidst failed harvests and the threat of AIDS,...",2008-01-01
9543,Timber!,"Mystery, Adventure",en,"Leo Carrillo (Quebec), Andy Devine (Arizona), ...",Two FBI agents are sent to investigate sabotag...,1942-08-01
8939,Time,Documentary,de,NaN,"A film of Hungarian folk artists, sharing thei...",1992-09-25
6172,Avan Aval,NaN,ta,"Devika Madhavan (), Chandrika (), Sachu (), Vi...",The story is based on real life incidents and ...,2016-04-08

In [3]:
df = df.dropna()

## 1. Lowercasing

In [4]:
df['description'] = df['description'].str.lower()
df.sample(5)

,title,genre,language,casts,description,release_date
3800,Fugitive,"Drama, TV Movie",en,"Stephen Rea (Peter), Eve Belton (Claire), Paul...","after 18 years as a friar, peter is no longer ...",1974-12-05
4049,Uprising,"Drama, History, War, TV Movie",en,"Leelee Sobieski (Tosia Altmann), Hank Azaria (...","in the warsaw ghetto in 1943, jews rise agains...",2001-11-04
7140,Ticket of No Return,Drama,de,"Tabea Blumenschein (Sie), Lutze (Trinkerin vo...",a sartorially resplendent woman of few words a...,1979-10-27
6926,Undertrial,Drama,hi,"Rajpal Yadav (Sagar Hussain), Kader Khan (), M...",sagar hussain is under trial accused of raping...,2007-02-09
7588,Faceless,Horror,en,"Helmut Berger (Dr. Frank Flamand), Brigitte La...",a detective investigating a missing model in p...,1988-01-31

## 2. Removing HTML Tags

In [5]:
## no html tags present

word = "The <title> element specifies a title for the HTML page (which is shown in the browser's title bar or in the page's tab)"

pattern = re.compile("<[^>]+>")
pattern.sub("",word)

"The  element specifies a title for the HTML page (which is shown in the browser's title bar or in the page's tab)"

## 3. Removing URLs

In [ ]:
## no html tags present

word = "Check https://openai.com and www.google.com now!"

pattern = re.compile(r"(?:https?://|www\.)[^\s]+")
pattern.sub("",word)

'Check  and  now!'

## 4. Removing Punctuation

### Using for loop

In [7]:
import string

In [8]:
df['description'][0]

"estranged half-brothers jonny and james reunite after their father's mysterious death. as they search for the truth, buried secrets reveal a conspiracy threatening to tear their family apart."

In [9]:
puctuations = string.punctuation
puctuations

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [10]:
# will take more time

def remove_puctuations(word):
    for c in puctuations:
        word = word.replace(c,"")
    return word

In [11]:
remove_puctuations(df['description'][2])

'after cracking the biggest case in zootopias history rookie cops judy hopps and nick wilde find themselves on the twisting trail of a great mystery when gary desnake arrives and turns the animal metropolis upside down to crack the case judy and nick must go undercover to unexpected new parts of town where their growing partnership is tested like never before'

In [12]:
# df['description'] = df['description'].apply(remove_puctuations)

In [13]:
df.sample(5)

,title,genre,language,casts,description,release_date
1965,The Entrepreneur,Drama,it,"Pierfrancesco Favino (Nicola), Carolina Cresce...","a small industrialist from turin, who inherite...",2011-01-13
9060,Scrappin',Comedy,de,"Lucas Gregorowicz (Mirko Talhammer), Frederick...",mirko talhammer is beyond himself when two str...,2016-05-05
7249,Kongsi,"Action, Comedy, Crime",ms,"Shaheizy Sam (Tumulak), Fizo Omar (ASP Shariff...","tumulak, a murderer sent by his employer, kimp...",2011-05-12
1850,Orange County,"Comedy, Drama",en,"Colin Hanks (Shaun Brumder), Jack Black (Lance...",shaun brumder is a local surfer kid from orang...,2002-01-11
2541,Dhairyam,"Drama, Romance",te,"Nithiin (Seenu), Raima Sen (Mallika), Tanikell...",seenu is the son of a municipality truck drive...,2005-02-12

### Using translate

In [14]:
# take less time

def remove_puctuations2(word):
    return word.translate(str.maketrans("","",puctuations))

In [15]:
df['description'][1]

'having found the safety of the greenland bunker after the comet clarke decimated the earth, the garrity family must now risk everything to embark on a perilous journey across the wasteland of europe to find a new home.'

In [16]:
df['description'] = df['description'].apply(remove_puctuations2)

## 5. Chat Word Treatment (Slang Expansion)

eg: ASAP -> As Soon As Possible

In [17]:
chat_words_dict = {}
with open("data/english_chat_words.txt","r") as file:
    for f in file.readlines():
        chat_words_dict[f.split("->")[0].strip()] = f.split("->")[1].strip()

    # chat_words.append(file.read().split("->"))

In [18]:
def remove_chatwords(sentence):
    result = str(sentence)
    for word in sentence.split(" "):
        if word.upper() in chat_words_dict:
            print(word)
            print(chat_words_dict[word.upper()])
            result = result.replace(word, chat_words_dict[word.upper()])
    return result

In [19]:
remove_chatwords("TBH I have to go ASAP to office")

TBH
To Be Honest
ASAP
As Soon As Possible

'To Be Honest I have to go As Soon As Possible to office'

In [20]:
df['description'].apply(remove_chatwords)

tba
To Be Announced
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
y
Why
tba
To Be Announced
tba
To Be Announced
aka
Also Known As
aka
Also Known As
ty
Thank You
ty
Thank You
ty
Thank You
tia
Thanks In Advance
diy
Do It Yourself
diy
Do It Yourself
aka
Also Known As
tba
To Be Announced
ty
Thank You
ooo
Out Of Office
aka
Also Known As
tia
Thanks In Advance
yt
YouTube
yt
YouTube
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
ty
Thank You
sos
Save Our Souls (Help)
op
Original Poster
u
You
aka
Also Known As

0       estranged halfbrothers jonny and james reunite...
1       having found the safety of the greenland bunke...
2       after cracking the biggest case in zootopias h...
3       macau police brings the tracking expert police...
4       a group of friends facing midlife crises head ...
                              ...
9994    during world war ii captain cassidy and his cr...
9996    after her car is towed and she is left with a ...
9997    the woman lets herself go so she can assuage h...
9998    set in the sleepy town of bawley point on the ...
9999    set in turnofthecentury new england this music...
Name: description, Length: 8876, dtype: str

In [21]:
df['description'] = df['description'].apply(remove_chatwords)

tba
To Be Announced
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
y
Why
tba
To Be Announced
tba
To Be Announced
aka
Also Known As
aka
Also Known As
ty
Thank You
ty
Thank You
ty
Thank You
tia
Thanks In Advance
diy
Do It Yourself
diy
Do It Yourself
aka
Also Known As
tba
To Be Announced
ty
Thank You
ooo
Out Of Office
aka
Also Known As
tia
Thanks In Advance
yt
YouTube
yt
YouTube
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
ty
Thank You
sos
Save Our Souls (Help)
op
Original Poster
u
You
aka
Also Known As

## Removing stopwords

In [22]:
import nltk
nltk.download('stopwords', download_dir='/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')
from nltk.corpus import stopwords
nltk.data.path.append(
    '/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data'
)

[nltk_data] Downloading package stopwords to /home/rathan-r-
[nltk_data]     nayak/Rathan/Machine Learning/machine-
[nltk_data]     leaning/NLP/TextPreprocessing/data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [24]:
def remove_stopwords(sentence):
    li = []

    for word in sentence.split(" "):
        if word not in stopwords.words('english'):
            li.append(word)
    return " ".join(li)

In [25]:
remove_stopwords("I was in office for long time")

'I office long time'

In [26]:
df['description'].apply(remove_stopwords)

0       estranged halfbrothers jonny james reunite fat...
1       found safety greenland bunker comet clarke dec...
2       cracking biggest case zootopias history rookie...
3       macau police brings tracking expert police off...
4       group friends facing midlife crises head rainf...
                              ...
9994    world war ii captain cassidy crew submariners ...
9996    car towed left shocking 21634 tow bill unhouse...
9997    woman lets go assuage erotic affliction provoc...
9998    set sleepy town bawley point nsw south coast b...
9999    set turnofthecentury new england musical tells...
Name: description, Length: 8876, dtype: str

In [27]:
df['description'] = df['description'].apply(remove_stopwords)

## Handling Emoji

In [28]:
import emoji

In [29]:
word = "I love NLP 🤖🔥"

emoji.replace_emoji(word, replace="")

'I love NLP '

In [30]:
df['description'] = df['description'].apply(lambda x: emoji.replace_emoji(x, replace="").strip())

## Spelling Correction

In [31]:
from textblob import TextBlob

In [32]:
incorrect_txt = "I wass walkisg to an offce"

text_blob = TextBlob(incorrect_txt)

text_blob.correct().string

'I was walking to an office'

In [ ]:
def fix_spellinga(sentence):
    text_blob = TextBlob(sentence)
    return text_blob.correct().string

In [1]:
df['description'] = df['description'].apply(fix_spelling)

NameError: name 'df' is not defined

## Tokenization

### NLTK

In [ ]:
from nltk.tokenize import word_tokenize

In [ ]:
word_tokenize("Dr. Smith paid Rs. 20 for Ph.D. books.")

['Dr.', 'Smith', 'paid', 'Rs', '.', '20', 'for', 'Ph.D.', 'books', '.']

In [ ]:
from nltk.tokenize import sent_tokenize

In [ ]:
sent_tokenize("Dr. Smith paid Rs. 20 for Ph.D. books.")

['Dr. Smith paid Rs.', '20 for Ph.D. books.']

### Spacy

In [ ]:
import spacy

In [ ]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("Dr. Smith paid Rs. 20 for Ph.D. books.")

In [ ]:
for text in doc:
    print(text)

Dr.
Smith
paid
Rs
.
20
for
Ph.D.
books
.

## Stemming

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
ps = PorterStemmer()

words = ["running", "played", "happiness", "daily"]

for word in words:
    print(ps.stem(word))

run
play
happi
daili

## Lemmatization

In [ ]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet', download_dir='/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')
nltk.data.path.append('/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')

lemmatizer = WordNetLemmatizer()

for word in words:
    print(lemmatizer.lemmatize(word=word, pos=wordnet.VERB))

[nltk_data] Downloading package wordnet to /home/rathan-r-
[nltk_data]     nayak/Rathan/Machine Learning/machine-
[nltk_data]     leaning/NLP/TextPreprocessing/data...

run
play
happiness
daily