In [152]:
import pandas as pd
import re

In [153]:
df = pd.read_csv("data/movies_data.csv")
df.sample(5)

,title,genre,language,casts,description,release_date
5662,The Charlatan,"Crime, Drama",hu,"Gyula Csortos (Tordai Dezsõ medikus), Tivadar ...",NaN,1917-09-10
9943,Lykkens musikanter,Comedy,da,"Dirch Passer (Elevatorfører Gogol), Ove Sprogø...",Villa Orfeus is a peculiar old house that has ...,1962-02-19
9838,Mrs. Recto,Drama,tl,"Regine Velasquez (), Elmo Magalona ()",Clara is a Recto shop owner who peddles fake c...,2010-09-03
6524,Azrail Peşimizde,Adventure,tr,"İrfan Atasoy (), Eva Bender (), Gönül Hancı ()...",Irfan is an engineer working in the Highways D...,1971-01-01
7727,Shabnam,Adventure,hi,"Mehmood (Khan Mustafa/Zingarro), L. Vijayalaks...",A faithful retainer tries to foil the plot to ...,1964-01-01

In [154]:
df = df.dropna()

## 1. Lowercasing

In [155]:
df['description'] = df['description'].str.lower()
df.sample(5)

,title,genre,language,casts,description,release_date
1519,The Count of Monte Cristo,"Adventure, Action, Drama",fr,Pierre Niney (Edmond Dantès / The Count of Mon...,edmond dantès becomes the target of a sinister...,2024-06-28
920,Franz,"Drama, History",cs,"Idan Weiss (Franz Kafka), Peter Kurth (Hermann...","conceived as a kaleidoscopic mosaic, the film ...",2025-09-25
7525,Lamb,Drama,en,"Liam Neeson (Michael Lamb), Hugh O'Conor (Owen...",michael lamb is a father questioning his calli...,1986-10-10
2356,An American Crime,"Crime, Drama, Horror",en,"Elliot Page (Sylvia Likens), Catherine Keener ...",the true story of suburban housewife gertrude ...,2007-07-27
5392,Heatwave,Drama,en,"Judy Davis (Kate Dean), Richard Moir (Stephen ...","during a christmas heatwave, a community activ...",1982-03-08

## 2. Removing HTML Tags

In [156]:
## no html tags present

word = "The <title> element specifies a title for the HTML page (which is shown in the browser's title bar or in the page's tab)"

pattern = re.compile("<[^>]+>")
pattern.sub("",word)

"The  element specifies a title for the HTML page (which is shown in the browser's title bar or in the page's tab)"

## 3. Removing URLs

In [157]:
## no html tags present

word = "Check https://openai.com and www.google.com now!"

pattern = re.compile(r"(?:https?://|www\.)[^\s]+")
pattern.sub("",word)

'Check  and  now!'

## 4. Removing Punctuation

### Using for loop

In [158]:
import string

In [159]:
df['description'][0]

"estranged half-brothers jonny and james reunite after their father's mysterious death. as they search for the truth, buried secrets reveal a conspiracy threatening to tear their family apart."

In [160]:
puctuations = string.punctuation
puctuations

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [161]:
# will take more time

def remove_puctuations(word):
    for c in puctuations:
        word = word.replace(c,"")
    return word

In [162]:
remove_puctuations(df['description'][2])

'after cracking the biggest case in zootopias history rookie cops judy hopps and nick wilde find themselves on the twisting trail of a great mystery when gary desnake arrives and turns the animal metropolis upside down to crack the case judy and nick must go undercover to unexpected new parts of town where their growing partnership is tested like never before'

In [163]:
# df['description'] = df['description'].apply(remove_puctuations)

In [164]:
df.sample(5)

,title,genre,language,casts,description,release_date
2681,Get Santa,"Comedy, Family",en,"Jim Broadbent (Santa Claus), Rafe Spall (Steve...",a father and son must team up to save christma...,2014-12-05
5908,Saltwater,"TV Movie, Science Fiction, Action, Horror",en,"Rachele Brooke Smith (Gina), Jeff Fahey (Rottg...",a group of lifeguards attempt to kill an atomi...,2016-07-24
9559,The Tokyo Siblings,Drama,ja,"Yuriko Hirooka (Yoshiko Hayashi), Urara Awata ...","living in an old tokyo district, kenichi works...",1995-01-14
2658,The Trespasser,Drama,en,"Gloria Swanson (Marion Donnell), Robert Ames (...",a stenographer who works for a lawyer falls in...,1929-11-11
5238,Pals,Drama,es,"Antonio Flores (Antonio), Rosario Flores (Rosa...",josé is an unemployed 18-year-old living in a ...,1982-10-25

### Using translate

In [165]:
# take less time

def remove_puctuations2(word):
    return word.translate(str.maketrans("","",puctuations))

In [166]:
df['description'][1]

'having found the safety of the greenland bunker after the comet clarke decimated the earth, the garrity family must now risk everything to embark on a perilous journey across the wasteland of europe to find a new home.'

In [167]:
df['description'] = df['description'].apply(remove_puctuations2)

## 5. Chat Word Treatment (Slang Expansion)

eg: ASAP -> As Soon As Possible

In [168]:
chat_words_dict = {}
with open("data/english_chat_words.txt","r") as file:
    for f in file.readlines():
        chat_words_dict[f.split("->")[0].strip()] = f.split("->")[1].strip()

    # chat_words.append(file.read().split("->"))

In [169]:
def remove_chatwords(sentence):
    result = str(sentence)
    for word in sentence.split(" "):
        if word.upper() in chat_words_dict:
            print(word)
            print(chat_words_dict[word.upper()])
            result = result.replace(word, chat_words_dict[word.upper()])
    return result

In [170]:
remove_chatwords("TBH I have to go ASAP to office")

TBH
To Be Honest
ASAP
As Soon As Possible

'To Be Honest I have to go As Soon As Possible to office'

In [171]:
df['description'].apply(remove_chatwords)

tba
To Be Announced
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
y
Why
tba
To Be Announced
tba
To Be Announced
aka
Also Known As
aka
Also Known As
ty
Thank You
ty
Thank You
ty
Thank You
tia
Thanks In Advance
diy
Do It Yourself
diy
Do It Yourself
aka
Also Known As
tba
To Be Announced
ty
Thank You
ooo
Out Of Office
aka
Also Known As
tia
Thanks In Advance
yt
YouTube
yt
YouTube
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
ty
Thank You
sos
Save Our Souls (Help)
op
Original Poster
u
You
aka
Also Known As

0       estranged halfbrothers jonny and james reunite...
1       having found the safety of the greenland bunke...
2       after cracking the biggest case in zootopias h...
3       macau police brings the tracking expert police...
4       a group of friends facing midlife crises head ...
                              ...
9994    during world war ii captain cassidy and his cr...
9996    after her car is towed and she is left with a ...
9997    the woman lets herself go so she can assuage h...
9998    set in the sleepy town of bawley point on the ...
9999    set in turnofthecentury new england this music...
Name: description, Length: 8876, dtype: str

In [172]:
df['description'] = df['description'].apply(remove_chatwords)

tba
To Be Announced
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
jk
Just Kidding
tba
To Be Announced
y
Why
tba
To Be Announced
tba
To Be Announced
aka
Also Known As
aka
Also Known As
ty
Thank You
ty
Thank You
ty
Thank You
tia
Thanks In Advance
diy
Do It Yourself
diy
Do It Yourself
aka
Also Known As
tba
To Be Announced
ty
Thank You
ooo
Out Of Office
aka
Also Known As
tia
Thanks In Advance
yt
YouTube
yt
YouTube
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
aka
Also Known As
ty
Thank You
sos
Save Our Souls (Help)
op
Original Poster
u
You
aka
Also Known As

## Removing stopwords

In [173]:
import nltk
nltk.download('stopwords', download_dir='/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')
from nltk.corpus import stopwords
nltk.data.path.append(
    '/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data'
)

[nltk_data] Downloading package stopwords to /home/rathan-r-
[nltk_data]     nayak/Rathan/Machine Learning/machine-
[nltk_data]     leaning/NLP/TextPreprocessing/data...
[nltk_data]   Package stopwords is already up-to-date!

In [174]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [175]:
def remove_stopwords(sentence):
    li = []

    for word in sentence.split(" "):
        if word not in stopwords.words('english'):
            li.append(word)
    return " ".join(li)

In [176]:
remove_stopwords("I was in office for long time")

'I office long time'

In [177]:
df['description'].apply(remove_stopwords)

0       estranged halfbrothers jonny james reunite fat...
1       found safety greenland bunker comet clarke dec...
2       cracking biggest case zootopias history rookie...
3       macau police brings tracking expert police off...
4       group friends facing midlife crises head rainf...
                              ...
9994    world war ii captain cassidy crew submariners ...
9996    car towed left shocking 21634 tow bill unhouse...
9997    woman lets go assuage erotic affliction provoc...
9998    set sleepy town bawley point nsw south coast b...
9999    set turnofthecentury new england musical tells...
Name: description, Length: 8876, dtype: str

In [178]:
df['description'] = df['description'].apply(remove_stopwords)

## Handling Emoji

In [179]:
import emoji

In [180]:
word = "I love NLP 🤖🔥"

emoji.replace_emoji(word, replace="")

'I love NLP '

In [181]:
df['description'] = df['description'].apply(lambda x: emoji.replace_emoji(x, replace="").strip())

## Spelling Correction

In [182]:
from textblob import TextBlob

In [183]:
incorrect_txt = "I wass walkisg to an offce"

text_blob = TextBlob(incorrect_txt)

text_blob.correct().string

'I was walking to an office'

In [184]:
def fix_spelling(sentence):
    text_blob = TextBlob(sentence)
    return text_blob.correct().string

In [186]:
df['description'] = df['description'].apply(fix_spelling)

KeyboardInterrupt:

## Tokenization

### NLTK

In [187]:
from nltk.tokenize import word_tokenize

In [188]:
word_tokenize("Dr. Smith paid Rs. 20 for Ph.D. books.")

['Dr.', 'Smith', 'paid', 'Rs', '.', '20', 'for', 'Ph.D.', 'books', '.']

In [189]:
from nltk.tokenize import sent_tokenize

In [190]:
sent_tokenize("Dr. Smith paid Rs. 20 for Ph.D. books.")

['Dr. Smith paid Rs.', '20 for Ph.D. books.']

### Spacy

In [191]:
import spacy

In [194]:
nlp = spacy.load("en_core_web_sm")

doc = nlp("Dr. Smith paid Rs. 20 for Ph.D. books.")

In [196]:
for text in doc:
    print(text)

Dr.
Smith
paid
Rs
.
20
for
Ph.D.
books
.

## Stemming

In [197]:
from nltk.stem import PorterStemmer

In [199]:
ps = PorterStemmer()

words = ["running", "played", "happiness", "daily"]

for word in words:
    print(ps.stem(word))

run
play
happi
daili

## Lemmatization

In [203]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet', download_dir='/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')
nltk.data.path.append('/home/rathan-r-nayak/Rathan/Machine Learning/machine-leaning/NLP/TextPreprocessing/data')

lemmatizer = WordNetLemmatizer()

for word in words:
    print(lemmatizer.lemmatize(word=word, pos=wordnet.VERB))

[nltk_data] Downloading package wordnet to /home/rathan-r-
[nltk_data]     nayak/Rathan/Machine Learning/machine-
[nltk_data]     leaning/NLP/TextPreprocessing/data...

run
play
happiness
daily